[package]
name = "mt1fox/blueberry"
description = "A lightweight framework module loader for Roblox - Created for my games used inside Vulpes Studios."
license = "MIT"
version = "1.8.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["README.md"]

[dependencies]